### PR TITLE
fix: add safe bank access handling in single and double stream blocks

### PR DESCRIPTION
**Pull request by Limbicnation**

### CODE REVIEW

**Comment by logtd** [comment]
Did you encounter an error with the bank code as is?

**Comment by Limbicnation** [comment]
@logtd Hi thank you for your message. Apologies for my late reply. When running the workflow I'm running into the error:

`RuntimeError: Key and Value must have the same sequence length`

I have the same guidance and Steps values for both unsampling and sampling workflow sections. Maybe you can help me to resolve this?

**Comment by Limbicnation** [comment]
@logtd I've pushed some experimental changes to handle the sequence length mismatch error: https://github.com/Limbicnation/ComfyUI-Fluxtapoz/commit/9248f98867b9707ecf8017e46677c7f0e48f56b4

**Comment by logtd** [comment]
Hey, thanks for opening the PR. I had to make some changes to adjust the layers for fireflow. I believe it covered your issue with the bank being unsafe, but let me know if it is still an issue for you.

**Pull request closed without merging**
